easy_admin:
    entities:
        RoutingRegisters:
            class: AppBundle\Entity\RoutingRegisters
            label: 'Routing Registers'
            list:
                title: 'Routing Registers'
                sort: ['metrica', 'ASC']
                
                actions:
                    - { name: 'edit', icon: 'pencil', label:false }
                    - { name: 'delete', icon: 'remove', label:false }
                    - { name: 'new', label: "Add new" }
                    - { name: '-search' }

                fields:
                    - { property: 'domain', label: 'Domain' }
                    - { property: 'ipEntrada', label: 'Incoming IP'}
                    - { property: 'protocoloEntrada', label: 'Incoming protocol'}
                    - { property: 'redOrigen', label: 'Origin network'}
                    - { property: 'ipSalida', label: 'Outgoing IP'}
                    - { property: 'metrica', label: 'Penalty'}

            form:
                fields:
                    - { property:'domain', label:'Domain' }
                    - { property:'ipEntrada', label:'Incoming IP' }
                    - { property:'portEntrada', label:'Incoming port' }
                    - { property:'protocoloEntrada', label:'Incoming protocol', type:'choice', type_options:{ choices:{"UDP":"UDP","TLS":"TLS","TCP":"TCP","WS":"WS", "WSS":"WSS"}} }
                    - { property:'redOrigen', label:'Origin network' }
                    - { property:'ipSalida', label:'Outgoing IP' }
                    - { property:'portSalida', label:'Outgoing port' }
                    - { property:'metrica', label:'Penalty' }
                    - { type:'group', label:'Registrar'}
                    - { property:'registrarServer', label:'Registrar Server' }
                    - { property:'registrarTransport', label:'Registrar transport', type:'choice', type_options:{ choices:{"UDP":"UDP","TLS":"TLS","TCP":"TCP","WS":"WS", "WSS":"WSS"}} }
                    - { property:'registrarPort', label:'Registrar port' }
